# modules/ui_strings.py
# UI strings configuration for multilingual support (PL/EN).
# This file contains a dictionary with translations for all user interface elements.

TRANSLATIONS = {
    "PL": {
        "title": "Warehouse — Raport palet",
        "upload_csv": "Wybierz plik raportu (CSV, separator ';')",
        "no_file": "Proszę załadować plik CSV, aby kontynuować.",
        "filters": "Filtry",
        "mandant": "Mandant",
        "artikel": "Artykuł (ARTIKELNR)",
        "mode": "Tryb kontroli",
        "mode_deleted": "Usunięte palety (OUT_DATE)",
        "mode_received": "Przyjęte palety (IN_DATE)",
        "date_mode": "Tryb daty",
        "single": "Pojedyncza data",
        "range": "Zakres",
        "from": "Od",
        "to": "Do",
        "table_result": "Lista palet — wynik filtra",
        "table_summary": "Suma usuniętych palet według artykułu",
        "orders_tab": "Zamówienia",
        "upload_orders": "Załaduj pliki zamówień (.csv lub .xlsx) — można wiele",
        "orders_help": "Program odczyta kolumny z plików zamówień i zbierze liczbę palet i ilość sztuk.",
        "orders_table": "Podsumowanie zamówień (agregat)",
        "compare": "Porównanie zamówień z usunięciami",
        "hide_zero_diff": "Ukryj pozycje bez rozbieżności",
        "download_csv": "Pobierz CSV (usunięte palety)",
        "download_excel": "Pobierz Excel (raport)",
        "install_openpyxl": "Zainstaluj openpyxl, aby pobierać Excel",
        "manual_orders": "Dodatkowe zamówienia (ręczne wpisy)",
        "notes": "Uwagi",
        "delete_selected": "Usuń zaznaczone",
        "add_manual": "Dodaj ręczne zamówienie",
        "invalid_artikel": "Nieprawidłowy ARTIKELNR. Wybierz z listy dostępnych artykułów.",
        "select_artikel": "Wybierz ARTIKELNR...",
        "delete": "Usuń",
        "settings": "Ustawienia",
        "settings_cartons": "Kartony (wyjątki)",
        "settings_pallets": "Palety/ramy",
        "settings_other": "Inne opakowania",
        "add_prefix": "Dodaj prefix",
        "remove_prefix": "Usuń prefix",
        "stock_tab": "Stan magazynowy",
        "stock_table_pids": "Stan magazynowy (z PID)",
        "stock_table_agg": "Stan magazynowy (agregat)",
        "stock_warning": "UWAGA: Pamiętaj, że aktualne stany magazynowe są poprawne tylko na moment załadowania pliku z danymi. Jeśli zakres dat wybrany przy generowaniu pliku był zbyt krótki, nie wszystkie palety mogą być widoczne. Dla pełnej i prawidłowej kontroli stanów magazynowych, plik w schaeflein.ihka.de powinien być generowany z datami od 01.01.2016 do dzisiaj.",
        "metric_total_pallets": "Łączna liczba palet",
        "metric_cartons": "Kartony",
        "metric_other_pkg": "Inne opakowania",
        "checkbox_cartons_only": "Pokaż tylko kartony",
        "stock_date_title": "Analiza stanów magazynowych na datę",
        "stock_date_label": "Wybierz datę/zakres (historia)",
        "stock_date_range_label": "Zakres dat dla analizy historycznej",
        "btn_auto_download": "🔄 Auto-pobieranie danych (IHKA)",
        "wifi_warning": "⚠️ Wymagane połączenie z siecią Wi-Fi organizacji (Schaeflein).",
        "dl_step_init": "Inicjalizacja przeglądarki Firefox...",
        "dl_step_login": "Logowanie do systemu...",
        "dl_step_nav": "Nawigacja do raportu...",
        "dl_step_params": "Ustawianie parametrów (Daty, Mandant)...",
        "dl_step_exec": "Generowanie tabeli (może to chwilę potrwać)...",
        "dl_step_download": "Pobieranie pliku CSV...",
        "dl_success": "Plik pobrany i załadowany pomyślnie!",
        "dl_error": "Błąd pobierania: ",
        "dl_network_error": "⚠️ Błąd sieci: Serwer nie ma dostępu do IHKA. Jeśli używasz chmury, pobierz plik ręcznie.",
        "btn_open_ihka": "🌐 Otwórz IHKA (Pobieranie ręczne)",
        "err_file_load": "Błąd wczytywania pliku: ",
        "err_missing_cols": "Plik nie zawiera wymaganych kolumn: ",
        "err_format": "Błąd formatu pliku",
        "err_process_download": "Wystąpił błąd podczas przetwarzania pobranego pliku.",
        "restore_session": "⚠️ Przywrócono dane z ostatniej sesji.",
        "clear_data": "🗑️ Wyczyść dane",
        "admin_login": "🔐 Admin",
        "password": "Hasło",
        "login": "Zaloguj",
        "tab_analysis": "Analiza zamówień vs palet",
        "tab_stock": "Stany magazynowe",
        "tab_stats": "📊 Statystyka",
        "tab_removal": "🗑️ Usuwanie palet",
        "tab_settings": "⚙️ Ustawienia",
        "import_data": "📥 Import danych",
        "offline_tool": "🛠️ Narzędzie Offline",
        "offline_desc": "Jeśli automat nie działa (np. w chmurze), pobierz to narzędzie, uruchom na komputerze w sieci Wi-Fi, a pobrany plik wgraj powyżej.",
        "download_script": "📥 Pobierz skrypt (.zip)",
        "analysis_header": "⚖️ Analiza dodanych i usuniętych palet",
        "received_pallets": "Przyjęte palety",
        "received_cartons": "Kartony (przyjęte)",
        "received_other": "Inne opakowania (przyjęte)",
        "deleted_pallets": "Usunięte palety",
        "deleted_cartons": "Usunięte kartony",
        "deleted_other": "Inne opakowania",
        "analysis_filters_title": "🔍 Filtry analizy",
        "lbl_mode": "Tryb",
        "opt_mode_out": "Wyjście",
        "opt_mode_in": "Wejście",
        "lbl_dates": "Daty",
        "opt_date_day": "Dzień",
        "lbl_date": "Data",
        "lbl_time": "Czas (1h)",
        "pallet_list_title": "📋 Lista palet",
        "pallet_list_summary": "∑ Podsumowanie listy palet",
        "daily_details_expander": "📊 Szczegóły przyjęć i usunięć według dnia",
        "daily_details_info": "Wybierz artykuł w filtrach, aby zobaczyć szczegółową tabelę po dniach.",
        "daily_receipts": "📥 Przyjęcia według dnia",
        "daily_no_receipts": "Brak przyjętych palet dla wybranego artykułu w wybranym zakresie dat.",
        "daily_removals": "🗑️ Usunięcia według dnia",
        "daily_no_removals": "Brak usuniętych palet dla wybranego artykułu w wybranym zakresie dat.",
        "daily_no_data": "Brak danych do analizy szczegółowej.",
        "no_pallets_in_filter": "Brak palet w wybranym zakresie filtrów.",
        "orders_header": "📦 Zamówienia",
        "clear_all_orders_btn": "🗑️ Usuń wszystkie pliki zamówień",
        "loaded_files_info": "Załadowano plików: {count} | Poprawnie odczytano: {valid}",
        "add_manual_item_header": "Dodaj pojedynczy artykuł do ręcznych zamówień",
        "manual_add_row_btn": "Dodaj wiersz",
        "manual_select_article_warning": "Wybierz ARTIKELNR przed dodaniem.",
        "manual_article_not_in_filter_warning": "Ten ARTIKELNR nie jest na liście filtrowanej, ale zostanie dodany ręcznie.",
        "manual_quantity_warning": "Podaj liczbę palet lub ilość sztuk przed dodaniem wiersza.",
        "manual_added_success": "Dodano artykuł {art} do ręcznych zamówień.",
        "manual_clear_all": "🗑 Usuń wszystkie ręczne zamówienia",
        "manual_cleared_success": "Wyczyszczono wszystkie ręczne zamówienia.",
        "manual_added_header": "Ręczne zamówienia dodane do agregatu",
        "manual_delete_selected": "🗑 Usuń zaznaczone wiersze",
        "manual_deleted_success": "Usunięto zaznaczone wiersze z ręcznych zamówień.",
        "no_manual_orders": "Brak ręcznych zamówień w agregacie.",
        "no_orders_data": "Brak danych z plików zamówień ani z ręcznych zamówień.",
        "manual_input_artikelnr": "ARTIKELNR",
        "manual_input_pallets": "Palety",
        "manual_input_qty": "Ilość sztuk",
        "col_remove": "Usuń",
        "col_ordered_pallets": "Zamówione_palety",
        "col_ordered_qty": "Zamówione_sztuki",
        "col_sources": "Źródła",
        "col_source_details": "Szczegóły_źródeł",
        "col_diff_pallets": "Różnica_Palety",
        "col_diff_qty": "Różnica_Sztuki",
        "col_diff_explanation": "Wyjaśnienie różnicy",
        "col_diff_days": "Dni z różnicą",
        "metric_articles_ordered": "Artykuły z zamówieniami",
        "metric_articles_removed": "Artykuły usunięte",
        "metric_articles_diff": "Artykuły z rozbieżnością",
        "diff_none": "Brak różnicy",
        "diff_pallets_less": "Usunięto o {val} palet mniej",
        "diff_pallets_more": "Usunięto o {val} palet więcej",
        "diff_pallets_none": "Brak różnicy w liczbie palet",
        "diff_qty_missing": "usunięto o {val} sztuk mniej",
        "diff_qty_excess": "usunięto o {val} sztuk więcej",
        "diff_qty_none": "brak różnicy w ilości sztuk",
        "diff_days_warning": "⚠️ Uwaga: Nie rozpoznano daty w nazwach {count} plików (np. {example}). Zamówienia z tych plików są wliczone w sumę ogólną, ale NIE pojawią się w kolumnie 'Dni z różnicą'.",
        "stock_filters_title": "🔍 Filtry dla stanów magazynowych",
        "stock_date_check": "Data sprawdzenia stanów",
        "stock_articles": "Artykuły",
        "stock_no_pallets": "Brak palet na magazynie.",
        "col_article": "Artykuł",
        "col_description": "Opis artykułu",
        "col_packaging": "Opakowanie",
        "col_pallet_count": "Ilość palet",
        "col_quantity": "Ilość sztuk",
        "col_qty_per_pallet": "Ilość na palecie",
        "col_pid": "PID",
        "col_place": "Miejsce",
        "history_header": "📈 Historia liczby palet na magazynie",
        "history_show_total": "Pokaż łączną liczbę palet",
        "history_show_cartons": "Pokaż kartony",
        "history_show_other": "Pokaż inne opakowania",
        "chart_total_label": "Suma wszystkich palet",
        "chart_cartons_label": "Tylko kartony",
        "chart_hover_date": "Data",
        "chart_hover_sum": "Suma",
        "chart_hover_cartons": "Kartony",
        "chart_y_axis": "Liczba palet",
        "history_no_data": "Brak danych do wyświetlenia historii.",
        "col_in_date": "Data przyjęcia",
        "col_in_time": "Godzina przyjęcia",
        "col_out_date": "Data wyjścia",
        "col_out_time": "Godzina wyjścia",
        "col_created_by": "Utworzył",
        "col_changed_date": "Data zmiany",
        "col_changed_time": "Godzina zmiany",
        "col_status": "Status",
        "col_deleted_pallets": "Usunięte palety",
        "col_deleted_qty": "Usunięte sztuki",
        "suffix_pallets": "palet",
        "suffix_rows": "wierszy",
        "stats_header": "📊 Statystyka magazynu",
        "stats_no_data_warning": "Brak danych magazynowych do zbudowania statystyk.",
        "stats_history_articles_filter": "Artykuły (filtr dla historii)",
        "stats_monthly_report_header": "📊 Raport miesięczny i rankingi",
        "stats_select_mandant_detail": "Wybierz Mandant do analizy szczegółowej",
        "stats_month_comparison_header": "Porównanie miesięcy (Obecny vs Poprzedni)",
        "stats_metric_received_month": "Przyjęte (Ten miesiąc)",
        "stats_metric_received_cartons": "Przyjęte Kartony",
        "stats_metric_deleted_month": "Usunięte (Ten miesiąc)",
        "stats_metric_deleted_cartons": "Usunięte Kartony",
        "stats_top5_header": "Rankingi artykułów (Top 5)",
        "stats_select_period": "Wybierz okres",
        "period_last_week": "Ostatni tydzień",
        "period_last_month": "Ostatni miesiąc",
        "period_last_3_months": "Ostatnie 3 miesiące",
        "period_last_year": "Ostatni rok",
        "stats_top_sent": "Najczęściej wysyłane (Top 5)",
        "stats_top_received": "Najczęściej przyjmowane (Top 5)",
        "stats_stagnant_header": "Palety składowane powyżej",
        "period_5_years": "5 lat",
        "period_3_years": "3 lat",
        "period_1_year": "1 roku",
        "period_6_months": "6 miesięcy",
        "stats_metric_old_pallets": "Liczba starych palet (>{period})",
        "stats_suffix_total": "% całości",
        "stats_show_stagnant_list": "Pokaż listę zalegających palet",
        "col_days_in_stock": "Dni na magazynie",
        "stats_no_stock": "Brak palet na stanie.",
        "removal_header": "🗑️ Usuwanie palet (Generator PID)",
        "removal_info": "Narzędzie pomaga dobrać palety do usunięcia na podstawie zamówienia, uwzględniając priorytet miejsc (WE/BL -> 2/02) oraz dopasowanie ilości.",
        "removal_warn_no_orders": "⚠️ Brak załadowanych plików zamówień. Przejdź do zakładki 'Analiza zamówień' i załaduj pliki.",
        "removal_warn_empty_orders": "⚠️ Brak danych zamówień.",
        "removal_select_file": "Wybierz plik zamówienia:",
        "removal_list_header": "### Lista pozycji do usunięcia",
        "removal_col_others": "##### 🏷️ Pozostałe",
        "removal_col_cartons": "##### 📦 Kartony",
        "removal_tag_carton": "📦 Karton",
        "removal_target_pal": "Cel: {val} pal.",
        "removal_target_qty": "Cel: {val} szt.",
        "removal_select_pid_label": "Wybierz PID dla {art}",
        "removal_summary_text": "Zamówiono: {p1} pal. / {q1} szt. | Wybrano: {p2} pal. / {q2} szt.",
        "removal_submit_btn": "Przelicz / Zatwierdź wybór",
        "removal_summary_diff_header": "### 📊 Podsumowanie różnic",
        "removal_no_pid_header": "**Artykuły bez wybranych PID (do usunięcia):**",
        "removal_all_assigned": "Wszystkie artykuły mają przypisane PID.",
        "removal_diff_table_header": "**Tabela różnic (Zamówienie vs Wybór):**",
        "removal_no_diff": "Brak różnic ilościowych!",
        "removal_strategy_caption": "\\* - Artykuł obsługiwany strategią 'Priorytet Palet' (ignorowanie ilości sztuk)",
        "removal_result_header": "### 📋 Wynik",
        "removal_pid_list_expander": "Lista PID ({count} szt.)",
        "removal_copy_caption": "✅ Skopiuj listę (ikona w rogu), a następnie zatwierdź usunięcie.",
        "removal_msg_removed": "Oznaczono {count} palet jako usunięte. Nie będą one sugerowane przy kolejnych analizach.",
        "removal_btn_confirm": "✅ Zatwierdź usunięcie (Ukryj te PIDy)",
        "removal_help_confirm": "Kliknij po skopiowaniu, aby oznaczyć te palety jako usunięte w bieżącej sesji.",
        "removal_toast_generated": "Lista PID została wygenerowana. Skopiuj dane i zatwierdź usunięcie.",
        "removal_no_selection": "Brak wybranych palet.",
        "settings_header": "⚙️ Ustawienia",
        "settings_sect1_header": "1. Wykluczenia z porównań",
        "settings_sect1_caption": "Artykuły do pominięcia w tabelach różnic",
        "settings_sect1_explanation": "**Wyjaśnienie:**\nArtykuły wykluczeń to pozycje, gdzie ilość w zamówieniu nie zgadza się z ilością w systemie.\nPomimo prawidłowej fizycznej wysyłki towaru, program może pokazywać różnice w paletach lub sztukach.\nDodanie takich artykułów do listy wykluczeń eliminuje fałszywe różnice w tabelach.",
        "settings_exact_match_header": "##### 🎯 Artykuły (dokładne dopasowanie)",
        "settings_exact_match_caption": "Wpisz pełne numery artykułów, jeden pod drugim.",
        "settings_prefix_header": "##### 🔤 Prefiksy (początek numeru)",
        "settings_prefix_caption": "Wpisz ciągi znaków, od których zaczynają się wykluczone artykuły.",
        "settings_btn_save_exceptions": "💾 Zapisz wyjątki",
        "settings_msg_exceptions_saved": "✅ Wyjątki zapisane pomyślnie",
        "settings_sect2_header": "2. Konfiguracja opakowań (Mandant 352)",
        "settings_sect2_caption": "Określ, które artykuły są kartonami, a które innymi opakowaniami, na podstawie ich prefiksów.",
        "settings_cartons_header": "##### 📦 Prefiksy Kartonów",
        "settings_cartons_caption": "Artykuły zaczynające się od tych znaków będą zliczane jako kartony.",
        "settings_other_pkg_header": "##### 🏷️ Inne opakowania",
        "settings_other_pkg_caption": "Prefiksy dla pozostałych typów opakowań (nie-paletowych).",
        "settings_btn_save_packaging": "💾 Zapisz konfigurację opakowań",
        "settings_msg_packaging_saved": "✅ Konfiguracja opakowań zapisana pomyślnie",
        "settings_sect3_header": "3. Strategie usuwania (Priorytet Palet)",
        "settings_sect3_caption": "Dla poniższych artykułów system będzie dobierał palety do usunięcia kierując się liczbą palet, a nie sumą sztuk.",
        "settings_strat_prefixes_header": "##### 🔢 Prefiksy artykułów",
        "settings_strat_prefixes_caption": "Wpisz prefiksy artykułów (np. '202671'), dla których 1 szt. w zamówieniu = 1 paleta fizyczna.",
        "settings_btn_save_strategies": "💾 Zapisz strategie",
        "settings_msg_strategies_saved": "✅ Strategie zapisane pomyślnie",
        "settings_strat_explanation": "ℹ️ **Jak to działa?**\n\nJeśli artykuł znajduje się na tej liście, algorytm w zakładce **Usuwanie palet** zignoruje ilość sztuk na palecie i spróbuje dobrać dokładnie tyle palet, ile wynika z zamówienia.\n\n**Przykład:**\nZamówienie: 1 szt. (co oznacza 1 paletę).\nStan: Paleta ma 4 sztuki.\n\nBez tej strategii: System szukałby palety z 1 sztuką.\nZ tą strategią: System weźmie paletę z 4 sztukami, bo liczy się 1 paleta.",
    },
    "EN": {
        "title": "Warehouse — Pallet Report",
        "upload_csv": "Select report file (CSV, separator ';')",
        "no_file": "Please upload a CSV file to continue.",
        "filters": "Filters",
        "mandant": "Mandant",
        "artikel": "Article (ARTIKELNR)",
        "mode": "Control Mode",
        "mode_deleted": "Deleted Pallets (OUT_DATE)",
        "mode_received": "Received Pallets (IN_DATE)",
        "date_mode": "Date Mode",
        "single": "Single Date",
        "range": "Range",
        "from": "From",
        "to": "To",
        "table_result": "Pallet List — Filter Result",
        "table_summary": "Deleted Pallets Summary by Article",
        "orders_tab": "Orders",
        "upload_orders": "Upload Order Files (.csv or .xlsx) — multiple allowed",
        "orders_help": "The program will read columns from order files and aggregate pallet counts and quantities.",
        "orders_table": "Orders Summary (Aggregate)",
        "compare": "Comparison: Orders vs Deletions",
        "hide_zero_diff": "Hide items with no discrepancies",
        "download_csv": "Download CSV (Deleted Pallets)",
        "download_excel": "Download Excel (Report)",
        "install_openpyxl": "Install openpyxl to download Excel",
        "manual_orders": "Additional Orders (Manual Entries)",
        "notes": "Notes",
        "delete_selected": "Delete Selected",
        "add_manual": "Add Manual Order",
        "invalid_artikel": "Invalid ARTIKELNR. Select from the available list.",
        "select_artikel": "Select ARTIKELNR...",
        "delete": "Delete",
        "settings": "Settings",
        "settings_cartons": "Cartons (Exceptions)",
        "settings_pallets": "Pallets/Frames",
        "settings_other": "Other Packaging",
        "add_prefix": "Add Prefix",
        "remove_prefix": "Remove Prefix",
        "stock_tab": "Stock Level",
        "stock_table_pids": "Stock Level (with PID)",
        "stock_table_agg": "Stock Level (Aggregate)",
        "stock_warning": "NOTE: Current stock levels are correct only as of the data file generation time. If the date range selected when generating the file was too short, not all pallets may be visible. For full and correct stock control, the file in schaeflein.ihka.de should be generated with dates from 01.01.2016 to today.",
        "metric_total_pallets": "Total Pallets",
        "metric_cartons": "Cartons",
        "metric_other_pkg": "Other Packaging",
        "checkbox_cartons_only": "Show Cartons Only",
        "stock_date_title": "Stock Analysis by Date",
        "stock_date_label": "Select Date/Range (History)",
        "stock_date_range_label": "Date Range for Historical Analysis",
        "btn_auto_download": "🔄 Auto-download Data (IHKA)",
        "wifi_warning": "⚠️ Requires connection to organization Wi-Fi (Schaeflein).",
        "dl_step_init": "Initializing Firefox browser...",
        "dl_step_login": "Logging into system...",
        "dl_step_nav": "Navigating to report...",
        "dl_step_params": "Setting parameters (Dates, Mandant)...",
        "dl_step_exec": "Generating table (this may take a moment)...",
        "dl_step_download": "Downloading CSV file...",
        "dl_success": "File downloaded and loaded successfully!",
        "dl_error": "Download Error: ",
        "dl_network_error": "⚠️ Network Error: Server cannot access IHKA. If using cloud, download file manually.",
        "btn_open_ihka": "🌐 Open IHKA (Manual Download)",
        "err_file_load": "Error loading file: ",
        "err_missing_cols": "File is missing required columns: ",
        "err_format": "File format error",
        "err_process_download": "An error occurred while processing the downloaded file.",
        "restore_session": "⚠️ Data restored from last session.",
        "clear_data": "🗑️ Clear Data",
        "admin_login": "🔐 Admin",
        "password": "Password",
        "login": "Login",
        "tab_analysis": "Orders vs Pallets Analysis",
        "tab_stock": "Stock Levels",
        "tab_stats": "📊 Statistics",
        "tab_removal": "🗑️ Pallet Removal",
        "tab_settings": "⚙️ Settings",
        "import_data": "📥 Import Data",
        "offline_tool": "🛠️ Offline Tool",
        "offline_desc": "If auto-download fails (e.g., in cloud), download this tool, run on a PC with Wi-Fi, and upload the file above.",
        "download_script": "📥 Download Script (.zip)",
        "analysis_header": "⚖️ Analysis of Added and Removed Pallets",
        "received_pallets": "Received Pallets",
        "received_cartons": "Cartons (Received)",
        "received_other": "Other Packaging (Received)",
        "deleted_pallets": "Deleted Pallets",
        "deleted_cartons": "Deleted Cartons",
        "deleted_other": "Other Packaging",
        "analysis_filters_title": "🔍 Analysis Filters",
        "lbl_mode": "Mode",
        "opt_mode_out": "Output",
        "opt_mode_in": "Input",
        "lbl_dates": "Dates",
        "opt_date_day": "Day",
        "lbl_date": "Date",
        "lbl_time": "Time (1h)",
        "pallet_list_title": "📋 Pallet List",
        "pallet_list_summary": "∑ Pallet List Summary",
        "daily_details_expander": "📊 Daily details of receipts and removals",
        "daily_details_info": "Select an article in filters to see detailed daily table.",
        "daily_receipts": "📥 Receipts by day",
        "daily_no_receipts": "No received pallets for selected article in selected date range.",
        "daily_removals": "🗑️ Removals by day",
        "daily_no_removals": "No removed pallets for selected article in selected date range.",
        "daily_no_data": "No data for detailed analysis.",
        "no_pallets_in_filter": "No pallets found in the selected filter range.",
        "orders_header": "📦 Orders",
        "clear_all_orders_btn": "🗑️ Remove all order files",
        "loaded_files_info": "Files loaded: {count} | Correctly read: {valid}",
        "add_manual_item_header": "Add single item to manual orders",
        "manual_add_row_btn": "Add row",
        "manual_select_article_warning": "Select ARTIKELNR before adding.",
        "manual_article_not_in_filter_warning": "This ARTIKELNR is not in the filtered list, but will be added manually.",
        "manual_quantity_warning": "Enter pallet count or quantity before adding row.",
        "manual_added_success": "Added article {art} to manual orders.",
        "manual_clear_all": "🗑 Clear all manual orders",
        "manual_cleared_success": "All manual orders cleared.",
        "manual_added_header": "Manual orders added to aggregate",
        "manual_delete_selected": "🗑 Delete selected rows",
        "manual_deleted_success": "Selected rows removed from manual orders.",
        "no_manual_orders": "No manual orders in aggregate.",
        "no_orders_data": "No data from order files or manual orders.",
        "manual_input_artikelnr": "ARTIKELNR",
        "manual_input_pallets": "Pallets",
        "manual_input_qty": "Quantity (pcs)",
        "col_remove": "Remove",
        "col_ordered_pallets": "Ordered_Pallets",
        "col_ordered_qty": "Ordered_Qty",
        "col_sources": "Sources",
        "col_source_details": "Source_Details",
        "col_diff_pallets": "Diff_Pallets",
        "col_diff_qty": "Diff_Qty",
        "col_diff_explanation": "Diff_Explanation",
        "col_diff_days": "Diff_Days",
        "metric_articles_ordered": "Articles with orders",
        "metric_articles_removed": "Removed articles",
        "metric_articles_diff": "Articles with discrepancy",
        "diff_none": "No difference",
        "diff_pallets_less": "Removed {val} pallets less",
        "diff_pallets_more": "Removed {val} pallets more",
        "diff_pallets_none": "No difference in pallet count",
        "diff_qty_missing": "removed {val} pcs less",
        "diff_qty_excess": "removed {val} pcs more",
        "diff_qty_none": "no difference in quantity",
        "diff_days_warning": "⚠️ Warning: Date not recognized in {count} filenames (e.g. {example}). Orders from these files are included in total, but will NOT appear in 'Diff_Days' column.",
        "stock_filters_title": "🔍 Stock Filters",
        "stock_date_check": "Stock Check Date",
        "stock_articles": "Articles",
        "stock_no_pallets": "No pallets in stock.",
        "col_article": "Article",
        "col_description": "Description",
        "col_packaging": "Packaging",
        "col_pallet_count": "Pallet Count",
        "col_quantity": "Quantity",
        "col_qty_per_pallet": "Qty per Pallet",
        "col_pid": "PID",
        "col_place": "Location",
        "history_header": "📈 Pallet Stock History",
        "history_show_total": "Show Total Pallets",
        "history_show_cartons": "Show Cartons",
        "history_show_other": "Show Other Packaging",
        "chart_total_label": "Total Pallets",
        "chart_cartons_label": "Cartons Only",
        "chart_hover_date": "Date",
        "chart_hover_sum": "Sum",
        "chart_hover_cartons": "Cartons",
        "chart_y_axis": "Pallet Count",
        "history_no_data": "No data to display history.",
        "col_in_date": "In Date",
        "col_in_time": "In Time",
        "col_out_date": "Out Date",
        "col_out_time": "Out Time",
        "col_created_by": "Created By",
        "col_changed_date": "Changed Date",
        "col_changed_time": "Changed Time",
        "col_status": "Status",
        "col_deleted_pallets": "Deleted Pallets",
        "col_deleted_qty": "Deleted Qty",
        "suffix_pallets": "pallets",
        "suffix_rows": "rows",
        "stats_header": "📊 Warehouse Statistics",
        "stats_no_data_warning": "No warehouse data available to build statistics.",
        "stats_history_articles_filter": "Articles (history filter)",
        "stats_monthly_report_header": "📊 Monthly Report and Rankings",
        "stats_select_mandant_detail": "Select Mandant for detailed analysis",
        "stats_month_comparison_header": "Month Comparison (Current vs Previous)",
        "stats_metric_received_month": "Received (This Month)",
        "stats_metric_received_cartons": "Received Cartons",
        "stats_metric_deleted_month": "Deleted (This Month)",
        "stats_metric_deleted_cartons": "Deleted Cartons",
        "stats_top5_header": "Article Rankings (Top 5)",
        "stats_select_period": "Select Period",
        "period_last_week": "Last Week",
        "period_last_month": "Last Month",
        "period_last_3_months": "Last 3 Months",
        "period_last_year": "Last Year",
        "stats_top_sent": "Most Sent (Top 5)",
        "stats_top_received": "Most Received (Top 5)",
        "stats_stagnant_header": "Pallets stored over",
        "period_5_years": "5 years",
        "period_3_years": "3 years",
        "period_1_year": "1 year",
        "period_6_months": "6 months",
        "stats_metric_old_pallets": "Old Pallets Count (>{period})",
        "stats_suffix_total": "% of total",
        "stats_show_stagnant_list": "Show stagnant pallets list",
        "col_days_in_stock": "Days in Stock",
        "stats_no_stock": "No pallets in stock.",
        "removal_header": "🗑️ Pallet Removal (PID Generator)",
        "removal_info": "This tool helps select pallets for removal based on the order, considering location priority (WE/BL -> 2/02) and quantity matching.",
        "removal_warn_no_orders": "⚠️ No order files loaded. Go to 'Orders Analysis' tab and upload files.",
        "removal_warn_empty_orders": "⚠️ No order data.",
        "removal_select_file": "Select order file:",
        "removal_list_header": "### Items to remove",
        "removal_col_others": "##### 🏷️ Others",
        "removal_col_cartons": "##### 📦 Cartons",
        "removal_tag_carton": "📦 Carton",
        "removal_target_pal": "Target: {val} pal.",
        "removal_target_qty": "Target: {val} pcs",
        "removal_select_pid_label": "Select PID for {art}",
        "removal_summary_text": "Ordered: {p1} pal. / {q1} pcs | Selected: {p2} pal. / {q2} pcs",
        "removal_submit_btn": "Recalculate / Confirm Selection",
        "removal_summary_diff_header": "### 📊 Difference Summary",
        "removal_no_pid_header": "**Articles without selected PIDs (to remove):**",
        "removal_all_assigned": "All articles have assigned PIDs.",
        "removal_diff_table_header": "**Difference Table (Order vs Selection):**",
        "removal_no_diff": "No quantity differences!",
        "removal_strategy_caption": "\\* - Article handled by 'Pallet Priority' strategy (ignoring quantity)",
        "removal_result_header": "### 📋 Result",
        "removal_pid_list_expander": "PID List ({count} pcs)",
        "removal_copy_caption": "✅ Copy the list (icon in corner), then confirm removal.",
        "removal_msg_removed": "Marked {count} pallets as removed. They will not be suggested in future analyses.",
        "removal_btn_confirm": "✅ Confirm Removal (Hide these PIDs)",
        "removal_help_confirm": "Click after copying to mark these pallets as removed in the current session.",
        "removal_toast_generated": "PID list generated. Copy data and confirm removal.",
        "removal_no_selection": "No pallets selected.",
        "settings_header": "⚙️ Settings",
        "settings_sect1_header": "1. Comparison Exclusions",
        "settings_sect1_caption": "Articles to skip in difference tables",
        "settings_sect1_explanation": "**Explanation:**\nExclusion articles are items where the order quantity does not match the system quantity.\nDespite correct physical shipment, the program might show discrepancies in pallets or pieces.\nAdding such articles to the exclusion list eliminates false differences in tables.",
        "settings_exact_match_header": "##### 🎯 Articles (Exact Match)",
        "settings_exact_match_caption": "Enter full article numbers, one per line.",
        "settings_prefix_header": "##### 🔤 Prefixes (Start of Number)",
        "settings_prefix_caption": "Enter character strings that excluded articles start with.",
        "settings_btn_save_exceptions": "💾 Save Exceptions",
        "settings_msg_exceptions_saved": "✅ Exceptions saved successfully",
        "settings_sect2_header": "2. Packaging Configuration (Mandant 352)",
        "settings_sect2_caption": "Define which articles are cartons and which are other packaging based on their prefixes.",
        "settings_cartons_header": "##### 📦 Carton Prefixes",
        "settings_cartons_caption": "Articles starting with these characters will be counted as cartons.",
        "settings_other_pkg_header": "##### 🏷️ Other Packaging",
        "settings_other_pkg_caption": "Prefixes for other packaging types (non-pallet).",
        "settings_btn_save_packaging": "💾 Save Packaging Config",
        "settings_msg_packaging_saved": "✅ Packaging configuration saved successfully",
        "settings_sect3_header": "3. Removal Strategies (Pallet Priority)",
        "settings_sect3_caption": "For the articles below, the system will select pallets for removal based on pallet count, not total quantity.",
        "settings_strat_prefixes_header": "##### 🔢 Article Prefixes",
        "settings_strat_prefixes_caption": "Enter article prefixes (e.g. '202671') where 1 ordered unit = 1 physical pallet.",
        "settings_btn_save_strategies": "💾 Save Strategies",
        "settings_msg_strategies_saved": "✅ Strategies saved successfully",
        "settings_strat_explanation": "ℹ️ **How it works?**\n\nIf an article is on this list, the algorithm in the **Pallet Removal** tab will ignore the quantity of pieces on the pallet and try to select exactly as many pallets as ordered.\n\n**Example:**\nOrder: 1 pc (which means 1 pallet).\nStock: Pallet has 4 pcs.\n\nWithout this strategy: System would look for a pallet with 1 pc.\nWith this strategy: System will take the pallet with 4 pcs because 1 pallet counts.",
    }
}

def get_translations(lang_code="PL"):
    """
    Retrieves the translation dictionary for the specified language code.
    
    Args:
        lang_code (str): Language code ('PL' or 'EN').
        
    Returns:
        dict: Dictionary containing UI strings.
    """
    return TRANSLATIONS.get(lang_code, TRANSLATIONS["PL"])
